In [1]:
import pandas as pd
from datetime import timedelta,datetime

In [2]:
# 设置列表最大行数为500 
pd.set_option('display.max_rows', 500)  
pd.set_option('display.width', 1000)  
pd.set_option('display.max_colwidth', 1000)

In [ ]:
# 将tab替换为空格，将替换连续的两个空格为一个空格,直到没有连续的空格以便于后面代码读取txt并以空格分列内容
def replace_double_spaces(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
    previous_length = len(content)
    while True:
        # tab替换为空格，替换连续的两个空格为一个空格
        content = content.replace("	", " ")
        content = content.replace("  ", " ")
        current_length = len(content)
        if current_length == previous_length:
            break
        previous_length = current_length    
    with open(file_path, 'w') as file:
        file.write(content)

In [3]:
#读取数据集名，中间过程，输出数据集名，表格列名['datatime_ymd','datatime_hms','did','d_value','activity','1','2','3','4','5','6','7']
filename = 'hh130.rawdata.txt'
filename_first = 'hh130.csv'
headers = ['Date','Time','Sensor','Translate01','Translate02','Message','SensorType']

In [ ]:
#调替换函数
replace_double_spaces(filename)

In [ ]:
#打开数据集
dataset = pd.read_csv(filename,delimiter=' ', header=None,names = headers)
#报错ParserError: Error tokenizing data. C error: Expected 6 fields in line 69, saw 8，取决于第一行定义了几列
dataset.head()

In [ ]:
# #判断activity要加几行
# activity1234 = data[data['2'].apply(lambda x: type(x) != float)]
# activity1234

In [ ]:
#提取年月日和hms到列表
date = dataset['Date'].tolist() 
time = dataset['Time'].tolist()

In [ ]:
#以\t合并年月日和hms，并放入表格中修整格式
date_time = []
for i in range(0,len(date)) :
    datetime_list = [date[i],time[i]]
    datetime_add = ' '.join(datetime_list)
    date_time.append(datetime_add)
dataset.rename(columns={'Date': 'Datetime'}, inplace=True)#重命名列名
dataset.loc[:,'Datetime'] = date_time#将修约好的时间放回df
dataset.drop(['Time'],axis = 1,inplace = True)#删除不需要的列
dataset.head()

In [ ]:
# 将不带毫秒的e_datetime增加毫秒
dataset.loc[dataset['Datetime'].str.contains(r'^[^.]*$'), 'Datetime']+= '.0'

In [ ]:
#对时间格式处理的函数
def round_timestamp(s):
    s = s.apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S.%f'))
    seconds = s.dt.microsecond  # 获取小数部分（秒）
    max_digits = seconds.map(lambda x: len(str(x))).max()
    seconds0 = seconds.map(lambda x: format(x / (10 ** max_digits), f'.{max_digits}f'))
    rounded_seconds = round(seconds0.astype(float))  # 四舍五入修约
    s = s.apply(lambda x: x.replace(microsecond=0))  # 将微秒部分置零
    s += pd.to_timedelta(rounded_seconds, unit='s')  # 加上修约后的秒数
    # 处理分界线
    #s = s.apply(lambda x: x.replace(year=2077))  # 将年份替换为2077
    #s = s.apply(lambda x: x.timestamp())  # 转换为timestamp数字
    return s

In [ ]:
time = round_timestamp(dataset['Datetime'].astype(str))

In [ ]:
dataset.loc[:,'Datetime'] = time#将修约好的时间放回df
dataset.head()

In [ ]:
#保存为csv格式
dataset.to_csv(filename_first,index = False)

In [4]:
# 读取CSV文件
dataset= pd.read_csv(filename_first)
dataset.head()

              Datetime Sensor Translate01 Translate02 Message      SensorType
0  2014-04-17 00:02:31  ZB106      Ignore      Ignore      OK  Control4-Radio
1  2014-04-17 00:04:24  ZB102      Ignore      Ignore      OK  Control4-Radio
2  2014-04-17 00:05:16  ZB010      Ignore      Ignore      OK  Control4-Radio
3  2014-04-17 00:05:19  ZB009      Ignore      Ignore      OK  Control4-Radio
4  2014-04-17 00:07:08  ZB103      Ignore      Ignore      OK  Control4-Radio

In [5]:
#读取Sensor,Translate01列的所有类型,去重并排列
sensor = dataset.loc[:, ['Sensor']] #读取
translate01 = dataset.loc[:, [ 'Translate01']]
sensor_id = sensor.drop_duplicates()#去重
translate01_id = translate01.drop_duplicates()
sensor_id =sensor_id.sort_values(by = 'Sensor',ascending = True)#以sensor这列排序
translate01_id= translate01_id.sort_values(by = 'Translate01',ascending = True)
sensor_id = sensor_id.reset_index(drop = True)#索引重排
translate01_id = translate01_id.reset_index(drop = True)
print(sensor_id)
print(translate01_id)

     Sensor
0   BATP001
1   BATP002
2   BATP003
3   BATP004
4   BATP005
5   BATP006
6   BATP007
7   BATP008
8   BATP009
9   BATP010
10  BATP011
11  BATP102
12  BATP103
13  BATP104
14     D002
15    LS001
16    LS002
17    LS003
18    LS004
19    LS005
20    LS006
21    LS007
22    LS008
23    LS009
24    LS010
25    LS011
26     M001
27     M002
28     M003
29     M004
30     M005
31     M006
32     M011
33    MA007
34    MA008
35    MA009
36    MA010
37     T102
38     T103
39     T104
40     T106
41    ZB001
42    ZB002
43    ZB003
44    ZB004
45    ZB005
46    ZB006
47    ZB007
48    ZB008
49    ZB009
50    ZB010
51    ZB011
52    ZB102
53    ZB103
54    ZB104
55    ZB106
   Translate01
0     Bathroom
1      Bedroom
2       Ignore
3      Kitchen
4   LivingRoom
5  OutsideDoor

In [6]:
#检查Sensor,Translate01列的特殊类型，并判断是否准备洗去,此处为可视化处理无实际意义
button = dataset[dataset['Sensor'].str.contains('Button')]#模糊检索带button
button = button.loc[:, ['Sensor', 'Translate01', 'Translate02', 'Message', 'SensorType']]#去掉时间
button = button.drop_duplicates()#去重
#button = sensor_type.sort_values(by = 'Sensor',ascending = True)#以sensor这列排序
print(button)

Empty DataFrame
Columns: [Sensor, Translate01, Translate02, Message, SensorType]
Index: []

In [7]:
#模糊检索要洗去的类型
wash_env = sensor_id[sensor_id['Sensor'].str.contains('BATP')| \
                      sensor_id['Sensor'].str.contains('ZB')| \
                      sensor_id['Sensor'].str.contains('ZBL')]
wash_env = wash_env.reset_index(drop = True)#索引重排
#保存为csv格式
wash_env.to_csv('wash_env.csv',index = False)
#wash_env

In [8]:
#删除洗去的类型
env = sensor_id[~sensor_id['Sensor'].isin(wash_env['Sensor'])]
env = env.reset_index(drop = True)#索引重排
env.columns = ['D_ID']#修改列名
env.to_csv('env.csv',index = False)

In [9]:
def data_trans(data, trans_relationship):
    for key in trans_relationship.keys():
        for column_key in trans_relationship[key].keys():
            data.loc[data['d_name'].str[0:2] == key, column_key] = trans_relationship[key][column_key]
    return data[['level','d_type','d_func','d_name']]

def room_trans(data, trans_relationship):
    for key in trans_relationship.keys():
        data[key] = trans_relationship[key]
    return data[['level','d_type','d_func','d_name']]

def data_comb(data1, data2):
    data = pd.concat([data1, data2]).sort_values(by=['level', 'd_type'])
    return data.reset_index(drop=True)

In [10]:
data = pd.read_csv('env.csv')
data = data.rename(columns = {'D_ID': 'd_name'})

In [11]:
rooms = translate01_id['Translate01'].tolist()#提取房间名为列表
df_rooms = pd.DataFrame(rooms, columns=['d_func'])

In [12]:
#把各对应关系编入字典
trans_relationship = {
    'D0': {'level': 2,   'd_type': 'sensor',     'd_func': 'door'       },
    'LS': {'level': 2,   'd_type': 'sensor',     'd_func': 'light'      },
    'M0': {'level': 2,   'd_type': 'sensor',     'd_func': 'motion'     },
    'MA': {'level': 2,   'd_type': 'sensor',     'd_func': 'ambient'    },
    'T1': {'level': 2,   'd_type': 'sensor',     'd_func': 'temperature'},
    'L0': {'level': 2,   'd_type': 'sensor',     'd_func': 'lamp'       },
    'Bu': {'level': 3,   'd_type': 'controller', 'd_func': 'button'     }
}
rooms_trans_relationship = {'level': 1,   'd_type': 'room',     'd_name': '/'       }

In [13]:
data1 = room_trans(df_rooms, rooms_trans_relationship)
data2 = data_trans(data, trans_relationship)

In [14]:
env = data_comb(data1, data2)
env.to_csv('env.csv',index = False)

In [15]:
# 读取CSV文件
data_env = pd.read_csv('env.csv')
data_env.head(10)

   level  d_type       d_func d_name
0    1.0    room     Bathroom      /
1    1.0    room      Bedroom      /
2    1.0    room       Ignore      /
3    1.0    room      Kitchen      /
4    1.0    room   LivingRoom      /
5    1.0    room  OutsideDoor      /
6    2.0  sensor         door   D002
7    2.0  sensor        light  LS001
8    2.0  sensor        light  LS002
9    2.0  sensor        light  LS003

In [16]:
#重命名数据集的Datetime，Sensor，Message列，找到数据集中d_name列冗余数据
dataset = dataset.rename(columns = {'Datetime': 'ts','Sensor': 'd_name','Message': 'd_value'})
d_name = data_env['d_name'].tolist()
error_d_name = dataset[~dataset['d_name'].isin(d_name)]
error_d_name

                          ts d_name Translate01 Translate02 d_value      SensorType
0        2014-04-17 00:02:31  ZB106      Ignore      Ignore      OK  Control4-Radio
1        2014-04-17 00:04:24  ZB102      Ignore      Ignore      OK  Control4-Radio
2        2014-04-17 00:05:16  ZB010      Ignore      Ignore      OK  Control4-Radio
3        2014-04-17 00:05:19  ZB009      Ignore      Ignore      OK  Control4-Radio
4        2014-04-17 00:07:08  ZB103      Ignore      Ignore      OK  Control4-Radio
...                      ...    ...         ...         ...     ...             ...
1156628  2014-12-23 15:35:51  ZB010      Ignore      Ignore      OK  Control4-Radio
1156650  2014-12-23 15:36:43  ZB106      Ignore      Ignore      OK  Control4-Radio
1156651  2014-12-23 15:36:45  ZB004      Ignore      Ignore      OK  Control4-Radio
1156746  2014-12-23 15:38:35  ZB003      Ignore      Ignore      OK  Control4-Radio
1156771  2014-12-23 15:40:24  ZB011      Ignore      Ignore      OK  Control4-Radio

[199421 rows x 6 columns]

In [17]:
#模糊检索要洗去Button的TAP_COUNT，RELEASE
drop_button = dataset[dataset['d_value'].str.contains('TAP_COUNT')| \
                      dataset['d_value'].str.contains('HOLD_DEPRESS')| \
                      dataset['d_value'].str.contains('HOLD_RELEASE')| \
                      dataset['d_value'].str.contains('RELEASE')]
drop_button.head(10)

Empty DataFrame
Columns: [ts, d_name, Translate01, Translate02, d_value, SensorType]
Index: []

In [19]:
#合并需洗去的数据  
wash_data  = pd.concat([error_d_name ,drop_button])

In [22]:
# 将d_value的单一判断类结果值转换为0/1数值
dataset['d_value'] = dataset['d_value'].replace({"ON": 1.0, "OFF": 0.0, "OPEN": 1.0, "CLOSE": 0.0})
dataset.head(20)

                     ts d_name Translate01  Translate02 d_value            SensorType
0   2014-04-17 00:27:53   T104      Ignore  KitchenTemp      19  Control4-Temperature
1   2014-04-17 06:39:28  LS003      Ignore       Ignore      03  Control4-LightSensor
2   2014-04-17 06:39:31  LS006      Ignore       Ignore      01  Control4-LightSensor
3   2014-04-17 06:39:41  LS005      Ignore       Ignore      01  Control4-LightSensor
4   2014-04-17 06:39:42  LS001      Ignore       Ignore      01  Control4-LightSensor
5   2014-04-17 06:42:33  LS008      Ignore       Ignore      02  Control4-LightSensor
6   2014-04-17 06:42:40  LS007      Ignore       Ignore      01  Control4-LightSensor
7   2014-04-17 06:47:28  LS009      Ignore       Ignore      01  Control4-LightSensor
8   2014-04-17 06:49:28  LS003      Ignore       Ignore      05  Control4-LightSensor
9   2014-04-17 06:49:30  LS006      Ignore       Ignore      03  Control4-LightSensor
10  2014-04-17 06:49:39  LS011      Ignore       Ignore      01  Control4-LightSensor
11  2014-04-17 06:49:41  LS005      Ignore       Ignore      03  Control4-LightSensor
12  2014-04-17 06:49:42  LS001      Ignore       Ignore      04  Control4-LightSensor
13  2014-04-17 06:52:33  LS008      Ignore       Ignore      04  Control4-LightSensor
14  2014-04-17 06:52:39  LS007      Ignore       Ignore      02  Control4-LightSensor
15  2014-04-17 06:57:27  LS009      Ignore       Ignore      02  Control4-LightSensor
16  2014-04-17 06:59:28  LS003      Ignore       Ignore      06  Control4-LightSensor
17  2014-04-17 06:59:41  LS005      Ignore       Ignore      04  Control4-LightSensor
18  2014-04-17 06:59:42  LS001      Ignore       Ignore      05  Control4-LightSensor
19  2014-04-17 07:02:33  LS008      Ignore       Ignore      05  Control4-LightSensor

In [23]:
# 搜索d_value的未转换成01的数据
character_values = dataset[dataset['d_value'].apply(lambda x: isinstance(x, str))]['d_value']
character_values

0         19
1         03
2         01
3         01
4         01
          ..
957330    10
957333    09
957335    10
957373    09
957379    08
Name: d_value, Length: 206767, dtype: object

In [24]:
# 去除重复值，得到唯一的字符数据列表
my_list = list(character_values.unique())
f_list = my_list.copy()
print(f_list)
for value in my_list:
    try:
        if float(value)<=60:
            f_list.pop(f_list.index(value))
    except:
        pass

error_value = pd.DataFrame()
for charv in f_list:
    error_value = pd.concat([error_value, dataset[dataset['d_value'] == charv]])
error_value

['19', '03', '01', '02', '05', '04', '06', '09', '07', '22', '00', '08', '20', '10', '41', '33', '34', '12', '35', '11', '42', '14', '13', '24', '43', '36', '23', '25', '26', '15', '16', '17', '18', '52', '51', '32', '31', '30', '29', '50', '21', '28', '53', '39', '40', '27', '45', '46', '47', '44', '37', '49', '48', '38', '54', '56', '55', '57', '58', '60', '59', '61', '62', '64', '63', '65', '68', '66', '67', '69', '98', '24.0', '23.0', '23.5', '24.5', '25.0', '25.5', '22.5', '22.0', '21.5', '21.0', '20.5', '20.0', '19.5', '26.0', '26.5']

                         ts d_name Translate01 Translate02 d_value            SensorType
214451  2014-07-27 09:13:10  LS006      Ignore      Ignore      61  Control4-LightSensor
246130  2014-08-02 10:39:14  LS006      Ignore      Ignore      61  Control4-LightSensor
295785  2014-08-12 10:13:25  LS006      Ignore      Ignore      61  Control4-LightSensor
366737  2014-08-25 10:08:09  LS006      Ignore      Ignore      61  Control4-LightSensor
366831  2014-08-25 10:48:09  LS006      Ignore      Ignore      61  Control4-LightSensor
404858  2014-09-01 11:05:15  LS006      Ignore      Ignore      61  Control4-LightSensor
404859  2014-09-01 11:05:16  LS007      Ignore      Ignore      61  Control4-LightSensor
404984  2014-09-01 12:42:27  LS006      Ignore      Ignore      61  Control4-LightSensor
405057  2014-09-01 12:47:28  LS006      Ignore      Ignore      61  Control4-LightSensor
405240  2014-09-01 12:57:18  LS006      Ignore      Ignore      61  Control4-LightSensor
516098  2014-09-16 11:19:29  LS006      Ignore      Ignore      61  Control4-LightSensor
516114  2014-09-16 11:19:42  LS006      Ignore      Ignore      61  Control4-LightSensor
517076  2014-09-16 12:09:24  LS006      Ignore      Ignore      61  Control4-LightSensor
517876  2014-09-16 12:57:17  LS006      Ignore      Ignore      61  Control4-LightSensor
517954  2014-09-16 12:58:35  LS006      Ignore      Ignore      61  Control4-LightSensor
517969  2014-09-16 12:59:04  LS006      Ignore      Ignore      61  Control4-LightSensor
568824  2014-09-22 11:56:32  LS006      Ignore      Ignore      61  Control4-LightSensor
568841  2014-09-22 12:03:54  LS006      Ignore      Ignore      61  Control4-LightSensor
642185  2014-09-30 08:40:20  LS007      Ignore      Ignore      61  Control4-LightSensor
658852  2014-10-02 08:44:21  LS007      Ignore      Ignore      61  Control4-LightSensor
658856  2014-10-02 08:44:22  LS006      Ignore      Ignore      61  Control4-LightSensor
658876  2014-10-02 08:45:38  LS007      Ignore      Ignore      61  Control4-LightSensor
659337  2014-10-02 08:57:18  LS007      Ignore      Ignore      61  Control4-LightSensor
659624  2014-10-02 10:38:59  LS007      Ignore      Ignore      61  Control4-LightSensor
660631  2014-10-02 12:34:20  LS006      Ignore      Ignore      61  Control4-LightSensor
660684  2014-10-02 12:35:22  LS006      Ignore      Ignore      61  Control4-LightSensor
660735  2014-10-02 12:40:21  LS006      Ignore      Ignore      61  Control4-LightSensor
660820  2014-10-02 12:49:18  LS006      Ignore      Ignore      61  Control4-LightSensor
681039  2014-10-05 08:50:17  LS006      Ignore      Ignore      61  Control4-LightSensor
681071  2014-10-05 08:58:25  LS006      Ignore      Ignore      61  Control4-LightSensor
681202  2014-10-05 09:09:43  LS006      Ignore      Ignore      61  Control4-LightSensor
728054  2014-10-11 10:44:32  LS006      Ignore      Ignore      61  Control4-LightSensor
740188  2014-10-12 12:46:32  LS006      Ignore      Ignore      61  Control4-LightSensor
747820  2014-10-13 09:01:45  LS007      Ignore      Ignore      61  Control4-LightSensor
800724  2014-10-20 09:57:33  LS007      Ignore      Ignore      61  Control4-LightSensor
807250  2014-10-21 10:01:10  LS007      Ignore      Ignore      61  Control4-LightSensor
838804  2014-10-26 09:35:48  LS007      Ignore      Ignore      61  Control4-LightSensor
848438  2014-10-27 10:15:51  LS006      Ignore      Ignore      61  Control4-LightSensor
856606  2014-10-29 09:09:30  LS007      Ignore      Ignore      61  Control4-LightSensor
856998  2014-10-29 09:30:22  LS007      Ignore      Ignore      61  Control4-LightSensor
857203  2014-10-29 09:34:28  LS007      Ignore      Ignore      61  Control4-LightSensor
857422  2014-10-29 09:42:50  LS007      Ignore      Ignore      61  Control4-LightSensor
857459  2014-10-29 09:43:39  LS007      Ignore      Ignore      61  Control4-LightSensor
857483  2014-10-29 09:45:13  LS007      Ignore      Ignore      61  Control4-LightSensor
857489  2014-10-29 09:45:42  LS007      Ignore      Ignore      61  Control4-LightSensor
857496  2014-10-29 09:45:55  LS007      Ignore      Ignore      61  Control4-LightSensor
857865  2014-10-29 09:54:47  LS007      Ignore      Ignore      61  Control4-LightSensor
874963  2014-11-01 13:49:35  LS006      Ignore      Ignore      61  Control4-LightSensor
874989  2014-11-01 13:51:37  LS006      Ignore      Ignore      61  Control4-LightSensor
940447  2014-11-29 10:28:23  LS010      Ignore      Ignore      61  Control4-LightSensor
942799  2014-11-30 08:49:02  LS006      Ignore      Ignore      61  Control4-LightSensor
942856  2014-11-30 09:50:55  LS009      Ignore      Ignore      61  Control4-LightSensor
942892  2014-11-30 10:40:43  LS010      Ignore      Ignore      61  Control4-LightSensor
943278  2014-12-01 08:59:53  LS006      Ignore      Ignore      61  Control4-LightSensor
943299  2014-12-01 09:21:04  LS010      Ignore      Ignore      61  Control4-LightSensor
943344  2014-12-01 10:20:01  LS009      Ignore      Ignore      61  Control4-LightSensor
943364  2014-12-01 10:41:04  LS010      Ignore      Ignore      61  Control4-LightSensor
943819  2014-12-02 08:49:59  LS006      Ignore      Ignore      61  Control4-LightSensor
943879  2014-12-02 10:01:22  LS009      Ignore      Ignore      61  Control4-LightSensor
943910  2014-12-02 10:41:24  LS010      Ignore      Ignore      61  Control4-LightSensor
943924  2014-12-02 11:01:22  LS009      Ignore      Ignore      61  Control4-LightSensor
943932  2014-12-02 11:10:13  LS006      Ignore      Ignore      61  Control4-LightSensor
944460  2014-12-03 09:47:30  LS010      Ignore      Ignore      61  Control4-LightSensor
946860  2014-12-08 10:09:56  LS009      Ignore      Ignore      61  Control4-LightSensor
946881  2014-12-08 10:24:13  LS009      Ignore      Ignore      61  Control4-LightSensor
949562  2014-12-14 09:26:14  LS010      Ignore      Ignore      61  Control4-LightSensor
949600  2014-12-14 10:06:35  LS009      Ignore      Ignore      61  Control4-LightSensor
949601  2014-12-14 10:06:52  LS003      Ignore      Ignore      61  Control4-LightSensor
949633  2014-12-14 10:46:14  LS010      Ignore      Ignore      61  Control4-LightSensor
950032  2014-12-15 11:02:37  LS010      Ignore      Ignore      61  Control4-LightSensor
951445  2014-12-19 10:46:10  LS010      Ignore      Ignore      61  Control4-LightSensor
954514  2014-12-22 11:11:53  LS010      Ignore      Ignore      61  Control4-LightSensor
214465  2014-07-27 09:53:10  LS006      Ignore      Ignore      62  Control4-LightSensor
404851  2014-09-01 11:01:53  LS007      Ignore      Ignore      62  Control4-LightSensor
404959  2014-09-01 12:09:51  LS006      Ignore      Ignore      62  Control4-LightSensor
404972  2014-09-01 12:29:30  LS006      Ignore      Ignore      62  Control4-LightSensor
405044  2014-09-01 12:47:17  LS006      Ignore      Ignore      62  Control4-LightSensor
405071  2014-09-01 12:47:30  LS006      Ignore      Ignore      62  Control4-LightSensor
516106  2014-09-16 11:19:37  LS006      Ignore      Ignore      62  Control4-LightSensor
517868  2014-09-16 12:54:28  LS006      Ignore      Ignore      62  Control4-LightSensor
642559  2014-09-30 08:57:04  LS006      Ignore      Ignore      62  Control4-LightSensor
658848  2014-10-02 08:44:20  LS006      Ignore      Ignore      62  Control4-LightSensor
658880  2014-10-02 08:45:40  LS006      Ignore      Ignore      62  Control4-LightSensor
659386  2014-10-02 08:58:32  LS007      Ignore      Ignore      62  Control4-LightSensor
660262  2014-10-02 12:22:00  LS006      Ignore      Ignore      62  Control4-LightSensor
660463  2014-10-02 12:29:17  LS006      Ignore      Ignore      62  Control4-LightSensor
660502  2014-10-02 12:31:46  LS006      Ignore      Ignore      62  Control4-LightSensor
660599  2014-10-02 12:33:32  LS006      Ignore      Ignore      62  Control4-LightSensor
660606  2014-10-02 12:33:48  LS006      Ignore      Ignore      62  Control4-LightSensor
660639  2014-10-02 12:34:28  LS006      Ignore      Ignore      62  Control4-LightSensor
660688  2014-10-02 12:35:25  LS006      Ignore      Ignore      62  Control4-LightSensor
660694  2014-10-02 12:35:30  LS006      Ignore      Ignore      62  Control4-LightSensor
660699  2014-10-02 12:35:50  LS006      Ignore      Ignore      62  Control4-LightSensor
660782  2014-10-02 12:42:24  LS006      Ignore      Ignore      62  Control4-LightSensor
739788  2014-10-12 12:36:54  LS006      Ignore      Ignore      62  Control4-LightSensor
799512  2014-10-20 09:30:25  LS007      Ignore      Ignore      62  Control4-LightSensor
800671  2014-10-20 09:56:09  LS006      Ignore      Ignore      62  Control4-LightSensor
800717  2014-10-20 09:57:27  LS007      Ignore      Ignore      62  Control4-LightSensor
800726  2014-10-20 09:57:34  LS007      Ignore      Ignore      62  Control4-LightSensor
800739  2014-10-20 09:57:48  LS006      Ignore      Ignore      62  Control4-LightSensor
857573  2014-10-29 09:50:33  LS007      Ignore      Ignore      62  Control4-LightSensor
857787  2014-10-29 09:53:28  LS007      Ignore      Ignore      62  Control4-LightSensor
942829  2014-11-30 09:20:44  LS010      Ignore      Ignore      62  Control4-LightSensor
943377  2014-12-01 10:59:52  LS006      Ignore      Ignore      62  Control4-LightSensor
943850  2014-12-02 09:21:25  LS010      Ignore      Ignore      62  Control4-LightSensor
946767  2014-12-08 09:41:52  LS010      Ignore      Ignore      62  Control4-LightSensor
946797  2014-12-08 09:47:09  LS010      Ignore      Ignore      62  Control4-LightSensor
954491  2014-12-22 11:04:26  LS010      Ignore      Ignore      62  Control4-LightSensor
954550  2014-12-22 11:26:18  LS010      Ignore      Ignore      62  Control4-LightSensor
246124  2014-08-02 10:29:21  LS006      Ignore      Ignore      64  Control4-LightSensor
404839  2014-09-01 10:50:23  LS006      Ignore      Ignore      64  Control4-LightSensor
404845  2014-09-01 10:54:05  LS006      Ignore      Ignore      64  Control4-LightSensor
404953  2014-09-01 12:03:03  LS006      Ignore      Ignore      64  Control4-LightSensor
404964  2014-09-01 12:19:48  LS006      Ignore      Ignore      64  Control4-LightSensor
517336  2014-09-16 12:21:06  LS006      Ignore      Ignore      64  Control4-LightSensor
517655  2014-09-16 12:38:55  LS006      Ignore      Ignore      64  Control4-LightSensor
517672  2014-09-16 12:39:09  LS006      Ignore      Ignore      64  Control4-LightSensor
642560  2014-09-30 08:57:40  LS007      Ignore      Ignore      64  Control4-LightSensor
642713  2014-09-30 10:04:18  LS007      Ignore      Ignore      64  Control4-LightSensor
659422  2014-10-02 08:59:02  LS006      Ignore      Ignore      64  Control4-LightSensor
659522  2014-10-02 09:08:59  LS007      Ignore      Ignore      64  Control4-LightSensor
659857  2014-10-02 12:09:18  LS006      Ignore      Ignore      64  Control4-LightSensor
659885  2014-10-02 12:09:48  LS006      Ignore      Ignore      64  Control4-LightSensor
659892  2014-10-02 12:10:01  LS006      Ignore      Ignore      64  Control4-LightSensor
659906  2014-10-02 12:10:16  LS006      Ignore      Ignore      64  Control4-LightSensor
660407  2014-10-02 12:25:30  LS006      Ignore      Ignore      64  Control4-LightSensor
660417  2014-10-02 12:25:32  LS006      Ignore      Ignore      64  Control4-LightSensor
681356  2014-10-05 10:41:06  LS006      Ignore      Ignore      64  Control4-LightSensor
681368  2014-10-05 10:41:24  LS006      Ignore      Ignore      64  Control4-LightSensor
688959  2014-10-06 09:05:32  LS007      Ignore      Ignore      64  Control4-LightSensor
771767  2014-10-16 10:53:49  LS006      Ignore      Ignore      64  Control4-LightSensor
800842  2014-10-20 10:07:24  LS006      Ignore      Ignore      64  Control4-LightSensor
856888  2014-10-29 09:23:19  LS007      Ignore      Ignore      64  Control4-LightSensor
856918  2014-10-29 09:23:52  LS007      Ignore      Ignore      64  Control4-LightSensor
856945  2014-10-29 09:27:18  LS007      Ignore      Ignore      64  Control4-LightSensor
940424  2014-11-29 10:07:38  LS010      Ignore      Ignore      64  Control4-LightSensor
942838  2014-11-30 09:30:44  LS010      Ignore      Ignore      64  Control4-LightSensor
943307  2014-12-01 09:31:04  LS010      Ignore      Ignore      64  Control4-LightSensor
943349  2014-12-01 10:21:04  LS010      Ignore      Ignore      64  Control4-LightSensor
943860  2014-12-02 09:31:25  LS010      Ignore      Ignore      64  Control4-LightSensor
951408  2014-12-19 10:32:52  LS010      Ignore      Ignore      64  Control4-LightSensor
954450  2014-12-22 10:35:52  LS010      Ignore      Ignore      64  Control4-LightSensor
261182  2014-08-05 11:04:53  LS006      Ignore      Ignore      63  Control4-LightSensor
404864  2014-09-01 11:15:04  LS006      Ignore      Ignore      63  Control4-LightSensor
404869  2014-09-01 11:23:03  LS006      Ignore      Ignore      63  Control4-LightSensor
460281  2014-09-09 09:43:20  LS006      Ignore      Ignore      63  Control4-LightSensor
515735  2014-09-16 10:23:08  LS006      Ignore      Ignore      63  Control4-LightSensor
516119  2014-09-16 11:19:45  LS006      Ignore      Ignore      63  Control4-LightSensor
516249  2014-09-16 11:22:32  LS006      Ignore      Ignore      63  Control4-LightSensor
517814  2014-09-16 12:44:37  LS006      Ignore      Ignore      63  Control4-LightSensor
642254  2014-09-30 08:42:20  LS007      Ignore      Ignore      63  Control4-LightSensor
642718  2014-09-30 10:05:24  LS007      Ignore      Ignore      63  Control4-LightSensor
659248  2014-10-02 08:55:29  LS007      Ignore      Ignore      63  Control4-LightSensor
659249  2014-10-02 08:55:30  LS006      Ignore      Ignore      63  Control4-LightSensor
659418  2014-10-02 08:59:01  LS007      Ignore      Ignore      63  Control4-LightSensor
659592  2014-10-02 10:28:59  LS007      Ignore      Ignore      63  Control4-LightSensor
659869  2014-10-02 12:09:33  LS006      Ignore      Ignore      63  Control4-LightSensor
659890  2014-10-02 12:09:58  LS006      Ignore      Ignore      63  Control4-LightSensor
659900  2014-10-02 12:10:13  LS006      Ignore      Ignore      63  Control4-LightSensor
659927  2014-10-02 12:10:29  LS006      Ignore      Ignore      63  Control4-LightSensor
660415  2014-10-02 12:25:32  LS006      Ignore      Ignore      63  Control4-LightSensor
660422  2014-10-02 12:25:40  LS006      Ignore      Ignore      63  Control4-LightSensor
660455  2014-10-02 12:28:04  LS006      Ignore      Ignore      63  Control4-LightSensor
660526  2014-10-02 12:32:04  LS006      Ignore      Ignore      63  Control4-LightSensor
660601  2014-10-02 12:33:34  LS006      Ignore      Ignore      63  Control4-LightSensor
660614  2014-10-02 12:33:53  LS006      Ignore      Ignore      63  Control4-LightSensor
660691  2014-10-02 12:35:27  LS006      Ignore      Ignore      63  Control4-LightSensor
660697  2014-10-02 12:35:37  LS006      Ignore      Ignore      63  Control4-LightSensor
660707  2014-10-02 12:35:59  LS006      Ignore      Ignore      63  Control4-LightSensor
681211  2014-10-05 09:19:32  LS006      Ignore      Ignore      63  Control4-LightSensor
681366  2014-10-05 10:41:20  LS006      Ignore      Ignore      63  Control4-LightSensor
728039  2014-10-11 10:44:23  LS006      Ignore      Ignore      63  Control4-LightSensor
728067  2014-10-11 10:44:45  LS006      Ignore      Ignore      63  Control4-LightSensor
800834  2014-10-20 10:06:00  LS006      Ignore      Ignore      63  Control4-LightSensor
848434  2014-10-27 10:15:47  LS006      Ignore      Ignore      63  Control4-LightSensor
856857  2014-10-29 09:19:26  LS007      Ignore      Ignore      63  Control4-LightSensor
856898  2014-10-29 09:23:29  LS007      Ignore      Ignore      63  Control4-LightSensor
856906  2014-10-29 09:23:36  LS007      Ignore      Ignore      63  Control4-LightSensor
856951  2014-10-29 09:28:03  LS007      Ignore      Ignore      63  Control4-LightSensor
940439  2014-11-29 10:18:23  LS010      Ignore      Ignore      63  Control4-LightSensor
942885  2014-11-30 10:30:43  LS010      Ignore      Ignore      63  Control4-LightSensor
943334  2014-12-01 10:01:04  LS010      Ignore      Ignore      63  Control4-LightSensor
943356  2014-12-01 10:31:04  LS010      Ignore      Ignore      63  Control4-LightSensor
943902  2014-12-02 10:31:24  LS010      Ignore      Ignore      63  Control4-LightSensor
943921  2014-12-02 11:00:13  LS006      Ignore      Ignore      63  Control4-LightSensor
946847  2014-12-08 09:59:08  LS010      Ignore      Ignore      63  Control4-LightSensor
949574  2014-12-14 09:36:14  LS010      Ignore      Ignore      63  Control4-LightSensor
949624  2014-12-14 10:36:14  LS010      Ignore      Ignore      63  Control4-LightSensor
404840  2014-09-01 10:50:29  LS007      Ignore      Ignore      65  Control4-LightSensor
460301  2014-09-09 10:00:46  LS006      Ignore      Ignore      65  Control4-LightSensor
515741  2014-09-16 10:23:36  LS006      Ignore      Ignore      65  Control4-LightSensor
515748  2014-09-16 10:24:08  LS006      Ignore      Ignore      65  Control4-LightSensor
516130  2014-09-16 11:19:52  LS006      Ignore      Ignore      65  Control4-LightSensor
517088  2014-09-16 12:09:29  LS006      Ignore      Ignore      65  Control4-LightSensor
517299  2014-09-16 12:20:24  LS006      Ignore      Ignore      65  Control4-LightSensor
517527  2014-09-16 12:29:04  LS006      Ignore      Ignore      65  Control4-LightSensor
517663  2014-09-16 12:39:04  LS006      Ignore      Ignore      65  Control4-LightSensor
642225  2014-09-30 08:41:12  LS007      Ignore      Ignore      65  Control4-LightSensor
642231  2014-09-30 08:41:19  LS007      Ignore      Ignore      65  Control4-LightSensor
642250  2014-09-30 08:42:10  LS007      Ignore      Ignore      65  Control4-LightSensor
642259  2014-09-30 08:42:22  LS007      Ignore      Ignore      65  Control4-LightSensor
659523  2014-10-02 09:09:00  LS006      Ignore      Ignore      65  Control4-LightSensor
659556  2014-10-02 09:18:59  LS007      Ignore      Ignore      65  Control4-LightSensor
659587  2014-10-02 10:08:59  LS007      Ignore      Ignore      65  Control4-LightSensor
659724  2014-10-02 11:26:17  LS006      Ignore      Ignore      65  Control4-LightSensor
659798  2014-10-02 11:56:14  LS006      Ignore      Ignore      65  Control4-LightSensor
681219  2014-10-05 09:30:02  LS006      Ignore      Ignore      65  Control4-LightSensor
681354  2014-10-05 10:41:05  LS006      Ignore      Ignore      65  Control4-LightSensor
728071  2014-10-11 10:44:49  LS006      Ignore      Ignore      65  Control4-LightSensor
800665  2014-10-20 09:56:07  LS006      Ignore      Ignore      65  Control4-LightSensor
837817  2014-10-26 08:55:26  LS007      Ignore      Ignore      65  Control4-LightSensor
942877  2014-11-30 10:20:43  LS010      Ignore      Ignore      65  Control4-LightSensor
943319  2014-12-01 09:41:04  LS010      Ignore      Ignore      65  Control4-LightSensor
943339  2014-12-01 10:11:04  LS010      Ignore      Ignore      65  Control4-LightSensor
943891  2014-12-02 10:21:24  LS010      Ignore      Ignore      65  Control4-LightSensor
946883  2014-12-08 10:24:27  LS010      Ignore      Ignore      65  Control4-LightSensor
949584  2014-12-14 09:46:14  LS010      Ignore      Ignore      65  Control4-LightSensor
949617  2014-12-14 10:26:14  LS010      Ignore      Ignore      65  Control4-LightSensor
951382  2014-12-19 10:23:34  LS010      Ignore      Ignore      65  Control4-LightSensor
951393  2014-12-19 10:27:59  LS010      Ignore      Ignore      65  Control4-LightSensor
460289  2014-09-09 09:50:27  LS006      Ignore      Ignore      68  Control4-LightSensor
460369  2014-09-09 10:08:43  LS006      Ignore      Ignore      68  Control4-LightSensor
516625  2014-09-16 11:37:00  LS006      Ignore      Ignore      68  Control4-LightSensor

In [ ]:
#考虑要不要再次合并需洗去的数据  
#wash_data  = pd.concat([wash_data ,error_value])

In [20]:
# 清洗d_name异常数据
dataset = dataset.drop(wash_data.index)

In [21]:
#数据集索引重排
dataset = dataset.reset_index(drop = True)
dataset

                         ts d_name Translate01  Translate02 d_value            SensorType
0       2014-04-17 00:27:53   T104      Ignore  KitchenTemp      19  Control4-Temperature
1       2014-04-17 06:39:28  LS003      Ignore       Ignore      03  Control4-LightSensor
2       2014-04-17 06:39:31  LS006      Ignore       Ignore      01  Control4-LightSensor
3       2014-04-17 06:39:41  LS005      Ignore       Ignore      01  Control4-LightSensor
4       2014-04-17 06:39:42  LS001      Ignore       Ignore      01  Control4-LightSensor
...                     ...    ...         ...          ...     ...                   ...
957394  2014-12-23 15:41:35   M003  LivingRoom   LivingRoom     OFF       Control4-Motion
957395  2014-12-23 15:41:37   M003  LivingRoom   LivingRoom      ON       Control4-Motion
957396  2014-12-23 15:41:38   M003  LivingRoom   LivingRoom     OFF       Control4-Motion
957397  2014-12-23 15:41:48   M003  LivingRoom   LivingRoom      ON       Control4-Motion
957398  2014-12-23 15:41:50   M003  LivingRoom   LivingRoom     OFF       Control4-Motion

[957399 rows x 6 columns]

In [25]:
LEVEL = data_env['level'].tolist() #提取该列内容生成列表
D_TYPE = data_env['d_type'].tolist()
D_FUNC = data_env['d_func'].tolist() 
D_NAME = data_env['d_name'].tolist()
#COORDINATE = data_information['COORDINATE'].tolist()
#LAYER = data_information['LAYER'].tolist()
d_name = dataset['d_name'].tolist()

In [26]:
# 建立信息规则字典,LAYER[level]
information = {}
for level in range(0,len(D_NAME)) :
    information[D_NAME[level]]= [D_FUNC[level],LEVEL[level],D_TYPE[level]]

In [27]:
# 匹配信息并存入数据集
add_information = []
for i_d_name in d_name :
    add_information.append(information[i_d_name])
add_information

[['temperature', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['temperature', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['ambient', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['light', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],
 ['motion', 2.0, 'sensor'],

In [28]:
#生产data_add的df
dataset_add = pd.DataFrame(data = add_information,columns =['d_func','level','d_type'])
dataset_add

             d_func  level  d_type
0       temperature    2.0  sensor
1             light    2.0  sensor
2             light    2.0  sensor
3             light    2.0  sensor
4             light    2.0  sensor
...             ...    ...     ...
957394       motion    2.0  sensor
957395       motion    2.0  sensor
957396       motion    2.0  sensor
957397       motion    2.0  sensor
957398       motion    2.0  sensor

[957399 rows x 3 columns]

In [29]:
#匹配并加入'd_func','level','d_type'列
dataset_final = pd.merge(dataset,dataset_add,right_index =True,left_index = True)
dataset_final

                         ts d_name Translate01  Translate02 d_value            SensorType       d_func  level  d_type
0       2014-04-17 00:27:53   T104      Ignore  KitchenTemp      19  Control4-Temperature  temperature    2.0  sensor
1       2014-04-17 06:39:28  LS003      Ignore       Ignore      03  Control4-LightSensor        light    2.0  sensor
2       2014-04-17 06:39:31  LS006      Ignore       Ignore      01  Control4-LightSensor        light    2.0  sensor
3       2014-04-17 06:39:41  LS005      Ignore       Ignore      01  Control4-LightSensor        light    2.0  sensor
4       2014-04-17 06:39:42  LS001      Ignore       Ignore      01  Control4-LightSensor        light    2.0  sensor
...                     ...    ...         ...          ...     ...                   ...          ...    ...     ...
957394  2014-12-23 15:41:35   M003  LivingRoom   LivingRoom     0.0       Control4-Motion       motion    2.0  sensor
957395  2014-12-23 15:41:37   M003  LivingRoom   LivingRoom     1.0       Control4-Motion       motion    2.0  sensor
957396  2014-12-23 15:41:38   M003  LivingRoom   LivingRoom     0.0       Control4-Motion       motion    2.0  sensor
957397  2014-12-23 15:41:48   M003  LivingRoom   LivingRoom     1.0       Control4-Motion       motion    2.0  sensor
957398  2014-12-23 15:41:50   M003  LivingRoom   LivingRoom     0.0       Control4-Motion       motion    2.0  sensor

[957399 rows x 9 columns]

In [30]:
#生成由'ts','d_name','d_type','d_func','d_value'列组成的data
dataset_data = dataset_final[['ts','d_name','d_type','d_func','d_value']]

In [31]:
#模糊检索要env需要合并的ButtonUp和ButtonDown并删除
drop_data_env = data_env[data_env['d_name'].str.contains('ButtonDown')]
data_env = data_env.drop(drop_data_env.index)

In [32]:
#重命名ButtonUp为Button
data_env['d_name'] = data_env['d_name'].str.replace('ButtonUp', 'Button') 
data_env.to_csv('env.csv',index = False)

In [33]:
#将'd_name'列带有字符串'Buttonup'的行所对应的'd_value'列下该行的数据改为浮点数1。down为0
dataset_data.loc[dataset_data['d_name'].str.contains('ButtonUp'), 'd_value'] = 1.0
dataset_data.loc[dataset_data['d_name'].str.contains('ButtonDown'), 'd_value'] = 0

C:\Users\78785\AppData\Local\Temp\ipykernel_16884\2643777897.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_data.loc[dataset_data['d_name'].str.contains('ButtonUp'), 'd_value'] = 1.0
C:\Users\78785\AppData\Local\Temp\ipykernel_16884\2643777897.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_data.loc[dataset_data['d_name'].str.contains('ButtonDown'), 'd_value'] = 0

In [34]:
#重命名Button
dataset_data['d_name'] = dataset_data['d_name'].str.replace('ButtonUp', 'Button')
dataset_data['d_name'] = dataset_data['d_name'].str.replace('ButtonDown', 'Button')

C:\Users\78785\AppData\Local\Temp\ipykernel_16884\3038134514.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_data['d_name'] = dataset_data['d_name'].str.replace('ButtonUp', 'Button')
C:\Users\78785\AppData\Local\Temp\ipykernel_16884\3038134514.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_data['d_name'] = dataset_data['d_name'].str.replace('ButtonDown', 'Button')

In [35]:
#最终保存为csv格式
dataset_data.to_csv('data.csv',index = False)
wash_data.to_csv('wash.csv',index = False)